### PR TITLE
Add Path.exists assertion

### PR DESCRIPTION
**Pull request by yogurtearl**
gives a better error message and reads better than 
```kotlin
assertThat(Files.exists(regularFile)).isTrue()
```

### CODE REVIEW

**Comment by yogurtearl** [comment]
@evant is there something I need to do to get the build to work for this PR? just showing as "Unauthorized" on Circle.

**Comment by evant** [comment]
I don't know, will look at it when I get a chance. Likely no, you don't need to do anything.

**Review by evant — APPROVED** [review]

**Comment by evant** [comment]
Maybe circle was having a day? I re-ran it and it worked. Seems like there's an error in the test though

> Task :assertk:compileTestKotlinJvm FAILED
e: /home/circleci/code/assertk/src/jvmTest/kotlin/test/assertk/assertions/PathTest.kt: (21, 29): Unresolved reference: of

**Comment by evant** [comment]
Looks like it was because ci is running with java 8 and `Path.of` wasn't added until 11. The reason for this is because kotlin native was having issue on java 11 before. We may re-visit this but for now updated the test to use `Paths.get`.

**Pull request closed without merging**
