### PR TITLE
Add isEqualByComparingTo assertion methods

### PR DESCRIPTION
**Pull request by lukas-krecan**

### CODE REVIEW

**Comment by evant** [comment]
Can you give a concrete example where you'd want to use this over `isEqualTo()`? Just trying to understand the user-case.

**Comment by lukas-krecan** [comment]
The main use-case is comparing BigDecimals (as seen in the test) where 20.00 is not equal to 20 but it is equal when using comparator.

**Comment by evant** [comment]
Hm, makes sense. This other option would be to have a special `isEqualTo()` for BigDecimal that using `compareTo` under the hood, like we do for arrays. Not sure if that's more confusing though.

**Comment by lukas-krecan** [comment]
In my opinion, overloading `isEqualTo()` is indeed more confusing.

**Pull request merged**
