### PR TITLE
Upgrade to Gradle 8.0.2

### PR DESCRIPTION
**Pull request by JakeWharton**
Version catalogs are now stable and do not require enabling.

### CODE REVIEW

**Review by evant — APPROVED** [review]

**Comment by evant** [comment]
> 'compileJava' task (current target is 1.8) and 'compileKotlinJvm' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by JakeWharton** [comment]
Weird I thought I did a build locally. Anyway easy fix, but I'll do it tomorrow.

**Comment by JakeWharton** [comment]
Also should be good now

**Review by evant — APPROVED** [review]

**Comment by evant** [comment]
Fyi, looks like the update broke publishing https://app.circleci.com/pipelines/github/willowtreeapps/assertk/586/workflows/2cddc91e-0f93-4b08-a44c-d89ba6253ef6/jobs/1191

```
    Reason: Task ':assertk:publishAndroidNativeArm32PublicationToSonatypeRepository' uses this output of task ':assertk:signAndroidNativeArm64Publication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':assertk:signAndroidNativeArm64Publication' as an input of ':assertk:publishAndroidNativeArm32PublicationToSonatypeRepository'.
      2. Declare an explicit dependency on ':assertk:signAndroidNativeArm64Publication' from ':assertk:publishAndroidNativeArm32PublicationToSonatypeRepository' using Task#dependsOn.
      3. Declare an explicit dependency on ':assertk:signAndroidNativeArm64Publication' from ':assertk:publishAndroidNativeArm32PublicationToSonatypeRepository' using Task#mustRunAfter.
```

**Comment by JakeWharton** [comment]
Hmm should be fixed in a recent version of the publish plugin. I'm on mobile so I can check later.

**Comment by JakeWharton** [comment]
Oh nevermind this project uses a bespoke setup. I suspect it just needs to copy the workaround from the vannitech plugin.

**Comment by JakeWharton** [comment]
Seems like it is https://github.com/vanniktech/gradle-maven-publish-plugin/commit/b553c1be5a1821943efead28589ef1cf03d93124

**Comment by JakeWharton** [comment]
Sent a PR with a workaround. I linked the wrong one, it turns out.

**Pull request merged**
