### PR TITLE
Add flux assertion

### PR DESCRIPTION
**Pull request by Zomzog**
I think it can be useful to have assertions on coroutine flux directly.

I've tried it with JVM `containsExactly` and `index` but if you're ok with the proposal I can add others.

### CODE REVIEW

**Comment by evant** [comment]
Yeah, have considered flow assertions, I think something would be a good idea. A few bits of feedback for your pr:
1. Because of the dependency I do think they should be in a separate module.
2. The assertions you added assume the flow terminates, which may not always be the case. Need to look into good ways on asserting on non-terminating flows. [rxjava's test assertions](http://reactivex.io/RxJava/javadoc/io/reactivex/observers/TestObserver.html) may be some good inspiration here.

**Comment by evant** [comment]
Created my own pr https://github.com/willowtreeapps/assertk/pull/302 if you want to take a look. Some implementation decisions:

- Created a new artifact: `assertk-coroutines`
- The new flow assertions are all `suspend`. This allows you to use them on all supported platforms. In java, your likely to be wrapping your coroutine tests in a `runBlockingTest`, this plays nicely with that.
- `transform` has been made inline. This allows you to call suspend functions inside of it.
- Unstable coroutine api's are avoided for the most part. Except for cases where it's wrapping an unstable method: `count()`.
- Care is taken to support flows that don't complete when it makes sense.

**Comment by Zomzog** [comment]
Ok I've block on `transform` and created a dirty `coTransform` :)

How do you want to continue? You merge your PR and I rebase/rework my assertions on your way?

**Comment by evant** [comment]
Yep, that would work.

**Comment by evant** [comment]
In terms of assertions to be implemented for flow, I'm skeptical about `index()`. Unlike a list, a flow re-starts anytime it's consumed so something like
```kotlin
assertThat(actual).all {
   index(0).isPositive()
   index(1).isNegative()
}
```
which works well for lists wouldn't work well for flow.

**Comment by Zomzog** [comment]
For index with all yes, the flow will be partially consumed on each assertion. Flow has some notion of order so I'm not sure it is useless, but if you prefer I can remove it.

I've tried to allow using the `all` of your example. It forces me to expose some internal stuff. Maybe I'm doing it wrong?

**Comment by evant** [comment]
Sorry for the delay, yeah I don't think a duplicate `all` function is a good idea. We could make it inline for it to work here, though we may run into https://github.com/willowtreeapps/assertk/issues/298. Will have to think about it. For now, your `containsExactly` looks good, if you want to focus this pr on just that I'll merge it in.

**Comment by evant** [comment]
merged https://github.com/willowtreeapps/assertk/pull/321 which had containsExactly

**Pull request closed without merging**
