### PR TITLE
Add `asAssert` extensions

### PR DESCRIPTION
**Pull request by Goooler**
This is handy for simplifying things in https://github.com/GradleUp/shadow/blob/6c1920568d4c9c98ed5bb86ebf106a92ff63ef01/src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/util/file/TestFile.java#L280-L298

to

```kt
  fun assertExists(): TestFile = apply {
      asAssert().exists()
  }
```

### CODE REVIEW

**Comment by JakeWharton** [comment]
This seems a bit specialized for what is effectively saving four characters on `assertThat(this)`.

**Comment by Goooler** [comment]
They are convenient for sequence invocations like `true.assertThis().isTrue()`, and as extensions of what could be a part of idiomatic Kotlin usages.

**Comment by JakeWharton** [comment]
Hmm I would expect an extension in that form to be named `asAssert()` to fit in with other extension-based conversion functions.

**Comment by Goooler** [comment]
Makes sense!

**Comment by evant** [comment]
Sorry, this is to much of "multiple ways to do the same thing" that I want to avoid. There's other assertion libraries out there if you prefer a different style of assertion.

**Pull request closed without merging**
