### PR TITLE
Configure languageVersion via toolchain

### PR DESCRIPTION
**Pull request by Goooler**
Follow up #439.

https://kotlinlang.org/docs/gradle-configure-project.html#gradle-java-toolchains-support

### CODE REVIEW

**Comment by JakeWharton** [comment]
I believe this forces the installation of JDK 8 whereas mine will cross-compile using any available JDK.

**Comment by Goooler** [comment]
Yeah, I just noticed only JDK 16 was used on CI, we can add more JDKs if necessary.

**Comment by JakeWharton** [comment]
I would prefer not to land something like this, as the host JDK version should not matter since they can all cross-compile. We just need an appropriate minimum.

**Comment by Goooler** [comment]
Alright.

**Pull request closed without merging**
