### PR TITLE
Do not allow null-based assertions on non-null types

### PR DESCRIPTION
**Pull request by JakeWharton**
Before:
Screen Shot 2023-06-26 at 10 23 12 AM

After:
Screen Shot 2023-06-26 at 10 23 23 AM

### CODE REVIEW

**Comment by evant** [comment]
Clever! This doesn't break assertions on platform types right? I don't think it would?

**Comment by JakeWharton** [comment]
Sadly it selects the non-null variant :(

**Comment by JakeWharton** [comment]
I'm assuming that is a deal-breaker. I can't see a path forward. It's weird that it selects the non-null variant. I spent a little time trying to investigate ways to trick it and couldn't come up with anything.

**Comment by evant** [comment]
Yeah you'd need to assert both on a platform type. Could do something weird like only added them to the native variant? Not sure it's worth though.

**Pull request closed without merging**
